Repository CS2113-AY1819S1-T12-3/main, pull requests merged in 2018-11, with the labels that each got.

#173 fix conflicts between changeStatus and lost and found
  src/main/java/seedu/address/logic/commands/ChangeStatusCommand.java
  src/main/java/seedu/address/logic/commands/FoundCommand.java
  src/main/java/seedu/address/logic/commands/LostCommand.java
  src/main/java/seedu/address/model/item/Item.java
Labels: priority.high, type.bug

#205 save lost&found
  src/main/java/seedu/address/storage/XmlAdaptedItem.java
  src/test/java/seedu/address/storage/XmlAdaptedItemTest.java
Labels: priority.high, type.bug

#206 minor changes
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.medium, type.enhancement

#207 update the invalid message in lost command and found command
  src/main/java/seedu/address/logic/commands/FoundCommand.java
  src/main/java/seedu/address/logic/commands/LostCommand.java
Labels: priority.medium, severity.Medium, type.bug

#209 fix bugs in editcommand with lost&found
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.high, type.bug, type.task

#210 Done PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/gaoqikai.adoc
  docs/team/johndoe.adoc
Labels: priority.medium, type.task

#212 fixed PPP
  docs/DeveloperGuide.adoc
  docs/team/gaoqikai.adoc
Labels: priority.medium, type.task

#214 Included link to project code dashboard in PPP
  docs/team/kelvintankaiboon.adoc
Labels: type.task

#221 Section 2 DG class diagram update
  docs/images/DeleteItemSdForLogic.png
  docs/images/DeletePersonSdForLogic.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SDforDeleteItem.png
  docs/images/SDforDeleteItemEventHandling.png
  docs/images/SDforDeletePerson.png
  docs/images/SDforDeletePersonEventHandling.png
  docs/images/StorageClassDiagram.png
Labels: priority.high

#224 Fixed ContactUS
  docs/ContactUs.adoc
Labels: priority.low

#225 Updating PPP
  docs/DeveloperGuide.adoc
  docs/team/chewkinwhye.adoc
Labels: priority.high

#235 updated DG and fixed bug in editAccountCommand
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/EditAccountCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
Labels: priority.high

#237 fix ppp
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high, type.bug

#239 Update User Guide and Developer Guide
  .gitignore
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/SaveCommandSequenceDiagram.png
  src/main/resources/docs/template.xsl
Labels: priority.high, type.task

#246 V1.4
  docs/DeveloperGuide.adoc
  src/test/data/sandboxmanyItems.xml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SaveCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/AccountBuilder.java
  src/test/java/seedu/address/testutil/AccountListBuilder.java
  src/test/java/seedu/address/testutil/TypicalAccounts.java
Labels: priority.high

#248 Making Travis Work
  docs/DeveloperGuide.adoc
  src/test/java/seedu/address/logic/commands/LoanListCommandsTest.java
Labels: priority.high

#252 Edited Developer Guide and updated Ui.png
  docs/DeveloperGuide.adoc
  docs/images/Ui.png
Labels: priority.medium, type.task

#255 Added TagCommandTest
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/testutil/TypicalItems.java
Labels: priority.medium, type.task

#254 Implemented basic tests for OpenCommand
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/parser/OpenCommandParser.java
  src/test/java/seedu/address/logic/commands/OpenCommandTest.java
  src/test/java/seedu/address/logic/parser/OpenCommandParserTest.java
Labels: priority.high, type.task

#260 update lost&found test
  src/main/java/seedu/address/logic/commands/FoundCommand.java
  src/main/java/seedu/address/logic/commands/LostCommand.java
  src/test/java/seedu/address/testutil/LostandFoundFeatureTest.java
Labels: priority.high, status.ongoing, type.task

#269 Made some changes to Developer Guide
  docs/DeveloperGuide.adoc
Labels: priority.low, type.task

#272 Added sequence diagram
  docs/DeveloperGuide.adoc
  docs/diagrams/TagComponentSequenceDiagram.pptx
  docs/images/TagComponentSequenceDiagram.png
Labels: priority.medium, type.task

#270 update test cases
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/LostCommand.java
  src/main/java/seedu/address/logic/commands/LostandFoundCommand.java
  src/test/java/seedu/address/logic/commands/LostandFoundCommandTest.java
  src/test/java/seedu/address/testutil/LostandFoundFeatureTest.java
Labels: priority.high

#273 test cases done
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/FoundCommand.java
  src/main/java/seedu/address/logic/commands/LostandFoundCommand.java
  src/test/java/seedu/address/logic/commands/FoundCommandTest.java
  src/test/java/seedu/address/logic/commands/LostCommandTest.java
  src/test/java/seedu/address/logic/commands/LostandFoundCommandTest.java
Labels: priority.high, type.task
