Repository CS2113-AY1819S1-T12-3/main, pull requests merged in 2018-10, with the labels that each got.

#91 Taught saveCommand to save version of stockList as xml file with current date as file name
  src/main/java/seedu/address/storage/StorageManager.java
Labels: priority.high, type.enhancement

#93 Taught saveCommand to accept a file name from user and name the xml file accordingly
  src/main/java/seedu/address/commons/events/model/SaveStockListVersionEvent.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SaveCommandParser.java
  src/main/java/seedu/address/logic/parser/StockListParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.enhancement

#95 Update DeveloperGuide.adoc regarding SaveCommand
  docs/DeveloperGuide.adoc
Labels: priority.high, type.task

#96 Updated UserGuide.adoc and DeveloperGuide.adoc regarding SaveCommand
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high, type.task

#98 Basic dummy login feature with its associated commands
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StockListParser.java
  src/main/java/seedu/address/model/account/Account.java
  src/main/java/seedu/address/model/account/Password.java
  src/main/java/seedu/address/model/account/Username.java
Labels: priority.high, type.enhancement

#103 TagCommand: List items by a specific tag
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/StockListParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.task

#104 done UG&DG for tag
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/TagCommand.java
Labels: priority.high, type.task

#107 Improved UG and DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high, type.task

#110 For V1.2
  build.gradle
Labels: priority.high, type.story

#112 Wrote some JUnit tests for SaveCommand and SaveCommandParser
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SaveCommandParser.java
  src/test/java/seedu/address/logic/commands/SaveCommandTest.java
  src/test/java/seedu/address/logic/parser/SaveCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalFileNames.java
Labels: priority.high, type.task

#116 Changed the input parameters of changeStatus from index to name, created a status class and did minor morphing
  src/main/java/seedu/address/logic/commands/ChangeStatusCommand.java
  src/main/java/seedu/address/logic/parser/ChangeStatusCommandParser.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/Status.java
  src/main/java/seedu/address/storage/XmlAdaptedItem.java
  src/main/java/seedu/address/ui/ItemCard.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/storage/XmlAdaptedItemTest.java
  src/test/java/seedu/address/testutil/ItemBuilder.java
Labels: priority.medium

#117 Finished tag feature
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/item/TagContainsKeywordsPredicate.java
Labels: priority.high, type.task

#132 Finished AddTagCommand; changed UI.png
  Collate-TUI.jar
  collated/functional/ChewKinWhye.md
  collated/functional/gaoqikai.md
  collated/functional/kelvintankaiboon.md
  copyright.txt
  docs/images/Ui.png
  docs/images/damithc.jpg
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/StockListParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/item/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/stock_list_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.high, type.task

#134 fixed UGDG for addTag, edit, list
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high, type.story

#135 small fix
  README.adoc
  build.gradle
Labels: priority.medium

#142 Taught OpenCommand to create a OpenStockListVersionEvent and open a default html page when OpenCommand is called
  docs/fileaspage.html
  src/main/java/seedu/address/commons/events/model/OpenStockListVersionEvent.java
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/view/default.html
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.story

#154 fix little problems in lost&found
  src/main/java/seedu/address/logic/commands/FoundCommand.java
  src/main/java/seedu/address/logic/commands/LostCommand.java
Labels: priority.high, type.bug, type.enhancement

#156 fix bugs in lost&found
  src/main/java/seedu/address/logic/commands/FoundCommand.java
  src/main/java/seedu/address/logic/commands/LostCommand.java
Labels: priority.high, type.bug

#157 Updated DG and refactored code
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ChangeStatus.png
  docs/images/Status.png
  src/main/java/seedu/address/logic/commands/ChangeStatusCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLoanListCommand.java
  src/main/java/seedu/address/logic/commands/LoanListCommand.java
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/commands/ViewLoanListCommand.java
  src/main/java/seedu/address/logic/parser/ChangeStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteLoanListCommandParser.java
  src/main/java/seedu/address/logic/parser/LoanListCommandParser.java
  src/main/java/seedu/address/logic/parser/StockListParser.java
  src/main/java/seedu/address/model/item/LoanerDescription.java
  src/main/java/seedu/address/storage/XmlAdaptedLoanList.java
  src/main/java/seedu/address/storage/XmlAdaptedLoanerDescription.java
Labels: priority.high

#159 Implemented OpenCommand to open existing xml files in versions folder with a template xsl file.
  docs/fileaspage.html
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/parser/OpenCommandParser.java
  src/main/java/seedu/address/logic/parser/SaveCommandParser.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.high, type.story

#165 UGDG for deleteTag
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high, type.task
